// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reminders.proto

/*
Package reminders is a generated protocol buffer package.

It is generated from these files:
	reminders.proto

It has these top-level messages:
	ReminderConfig
	Reminder
	Empty
	ReminderList
	TaskList
*/
package reminders

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The state the task is in
type Reminder_ReminderState int32

const (
	Reminder_REPEATING  Reminder_ReminderState = 0
	Reminder_ASSIGNED   Reminder_ReminderState = 1
	Reminder_COMPLETE   Reminder_ReminderState = 2
	Reminder_UNASSIGNED Reminder_ReminderState = 3
)

var Reminder_ReminderState_name = map[int32]string{
	0: "REPEATING",
	1: "ASSIGNED",
	2: "COMPLETE",
	3: "UNASSIGNED",
}
var Reminder_ReminderState_value = map[string]int32{
	"REPEATING":  0,
	"ASSIGNED":   1,
	"COMPLETE":   2,
	"UNASSIGNED": 3,
}

func (x Reminder_ReminderState) String() string {
	return proto.EnumName(Reminder_ReminderState_name, int32(x))
}
func (Reminder_ReminderState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ReminderConfig struct {
	List  *ReminderList `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Tasks []*TaskList   `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *ReminderConfig) Reset()                    { *m = ReminderConfig{} }
func (m *ReminderConfig) String() string            { return proto.CompactTextString(m) }
func (*ReminderConfig) ProtoMessage()               {}
func (*ReminderConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReminderConfig) GetList() *ReminderList {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReminderConfig) GetTasks() []*TaskList {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Reminder struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	// Text day of the week
	DayOfWeek string `protobuf:"bytes,2,opt,name=day_of_week,json=dayOfWeek" json:"day_of_week,omitempty"`
	// The time this should next be run
	NextRunTime  int64                  `protobuf:"varint,3,opt,name=next_run_time,json=nextRunTime" json:"next_run_time,omitempty"`
	CurrentState Reminder_ReminderState `protobuf:"varint,4,opt,name=current_state,json=currentState,enum=reminders.Reminder_ReminderState" json:"current_state,omitempty"`
	// Assigned state for a github task
	GithubId string `protobuf:"bytes,5,opt,name=github_id,json=githubId" json:"github_id,omitempty"`
}

func (m *Reminder) Reset()                    { *m = Reminder{} }
func (m *Reminder) String() string            { return proto.CompactTextString(m) }
func (*Reminder) ProtoMessage()               {}
func (*Reminder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reminder) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Reminder) GetDayOfWeek() string {
	if m != nil {
		return m.DayOfWeek
	}
	return ""
}

func (m *Reminder) GetNextRunTime() int64 {
	if m != nil {
		return m.NextRunTime
	}
	return 0
}

func (m *Reminder) GetCurrentState() Reminder_ReminderState {
	if m != nil {
		return m.CurrentState
	}
	return Reminder_REPEATING
}

func (m *Reminder) GetGithubId() string {
	if m != nil {
		return m.GithubId
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReminderList struct {
	Reminders []*Reminder `protobuf:"bytes,1,rep,name=reminders" json:"reminders,omitempty"`
}

func (m *ReminderList) Reset()                    { *m = ReminderList{} }
func (m *ReminderList) String() string            { return proto.CompactTextString(m) }
func (*ReminderList) ProtoMessage()               {}
func (*ReminderList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReminderList) GetReminders() []*Reminder {
	if m != nil {
		return m.Reminders
	}
	return nil
}

type TaskList struct {
	Name  string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tasks *ReminderList `protobuf:"bytes,2,opt,name=tasks" json:"tasks,omitempty"`
}

func (m *TaskList) Reset()                    { *m = TaskList{} }
func (m *TaskList) String() string            { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()               {}
func (*TaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TaskList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskList) GetTasks() *ReminderList {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*ReminderConfig)(nil), "reminders.ReminderConfig")
	proto.RegisterType((*Reminder)(nil), "reminders.Reminder")
	proto.RegisterType((*Empty)(nil), "reminders.Empty")
	proto.RegisterType((*ReminderList)(nil), "reminders.ReminderList")
	proto.RegisterType((*TaskList)(nil), "reminders.TaskList")
	proto.RegisterEnum("reminders.Reminder_ReminderState", Reminder_ReminderState_name, Reminder_ReminderState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Reminders service

type RemindersClient interface {
	AddReminder(ctx context.Context, in *Reminder, opts ...grpc.CallOption) (*Empty, error)
	ListReminders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReminderList, error)
	AddTaskList(ctx context.Context, in *TaskList, opts ...grpc.CallOption) (*Empty, error)
}

type remindersClient struct {
	cc *grpc.ClientConn
}

func NewRemindersClient(cc *grpc.ClientConn) RemindersClient {
	return &remindersClient{cc}
}

func (c *remindersClient) AddReminder(ctx context.Context, in *Reminder, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/reminders.Reminders/AddReminder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindersClient) ListReminders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReminderList, error) {
	out := new(ReminderList)
	err := grpc.Invoke(ctx, "/reminders.Reminders/ListReminders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindersClient) AddTaskList(ctx context.Context, in *TaskList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/reminders.Reminders/AddTaskList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reminders service

type RemindersServer interface {
	AddReminder(context.Context, *Reminder) (*Empty, error)
	ListReminders(context.Context, *Empty) (*ReminderList, error)
	AddTaskList(context.Context, *TaskList) (*Empty, error)
}

func RegisterRemindersServer(s *grpc.Server, srv RemindersServer) {
	s.RegisterService(&_Reminders_serviceDesc, srv)
}

func _Reminders_AddReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reminder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindersServer).AddReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminders.Reminders/AddReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindersServer).AddReminder(ctx, req.(*Reminder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reminders_ListReminders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindersServer).ListReminders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminders.Reminders/ListReminders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindersServer).ListReminders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reminders_AddTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindersServer).AddTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reminders.Reminders/AddTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindersServer).AddTaskList(ctx, req.(*TaskList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reminders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reminders.Reminders",
	HandlerType: (*RemindersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddReminder",
			Handler:    _Reminders_AddReminder_Handler,
		},
		{
			MethodName: "ListReminders",
			Handler:    _Reminders_ListReminders_Handler,
		},
		{
			MethodName: "AddTaskList",
			Handler:    _Reminders_AddTaskList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reminders.proto",
}

func init() { proto.RegisterFile("reminders.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x6f, 0x94, 0x40,
	0x14, 0x5d, 0x96, 0x5d, 0x85, 0xcb, 0xb2, 0x92, 0xeb, 0x83, 0xa4, 0x26, 0x06, 0x79, 0xc2, 0x18,
	0x9b, 0x88, 0x89, 0x4f, 0xbe, 0x90, 0x8a, 0xcd, 0x9a, 0x76, 0xdb, 0xcc, 0x62, 0x7c, 0x24, 0x54,
	0x66, 0xdb, 0x09, 0x02, 0x0d, 0x33, 0xc4, 0xee, 0xef, 0xf0, 0xd7, 0xf8, 0xef, 0x0c, 0xc3, 0xc2,
	0x62, 0x16, 0xfb, 0x76, 0xef, 0x99, 0x73, 0xbf, 0xce, 0x19, 0x78, 0x56, 0xd1, 0x9c, 0x15, 0x29,
	0xad, 0xf8, 0xe9, 0x7d, 0x55, 0x8a, 0x12, 0xf5, 0x1e, 0x70, 0xef, 0x60, 0x49, 0xf6, 0xc9, 0x59,
	0x59, 0x6c, 0xd9, 0x2d, 0xbe, 0x85, 0xd9, 0x4f, 0xc6, 0x85, 0xad, 0x38, 0x8a, 0x67, 0xf8, 0x2f,
	0x4e, 0x0f, 0xc5, 0x1d, 0xf1, 0x82, 0x71, 0x41, 0x24, 0x09, 0xdf, 0xc0, 0x5c, 0x24, 0x3c, 0xe3,
	0xf6, 0xd4, 0x51, 0x3d, 0xc3, 0x7f, 0x3e, 0x60, 0x47, 0x09, 0xcf, 0x24, 0xb3, 0x65, 0xb8, 0xbf,
	0xa7, 0xa0, 0x75, 0x1d, 0x10, 0x61, 0x26, 0xe8, 0x43, 0x3b, 0x44, 0x27, 0x32, 0xc6, 0x57, 0x60,
	0xa4, 0xc9, 0x2e, 0x2e, 0xb7, 0xf1, 0x2f, 0x4a, 0x33, 0x7b, 0x2a, 0x9f, 0xf4, 0x34, 0xd9, 0x5d,
	0x6d, 0xbf, 0x53, 0x9a, 0xa1, 0x0b, 0x66, 0x41, 0x1f, 0x44, 0x5c, 0xd5, 0x45, 0x2c, 0x58, 0x4e,
	0x6d, 0xd5, 0x51, 0x3c, 0x95, 0x18, 0x0d, 0x48, 0xea, 0x22, 0x62, 0x39, 0xc5, 0x2f, 0x60, 0xfe,
	0xa8, 0xab, 0x8a, 0x16, 0x22, 0xe6, 0x22, 0x11, 0xd4, 0x9e, 0x39, 0x8a, 0xb7, 0xf4, 0x5f, 0x8f,
	0x5c, 0xd1, 0x07, 0x9b, 0x86, 0x48, 0x16, 0xfb, 0x3a, 0x99, 0xe1, 0x4b, 0xd0, 0x6f, 0x99, 0xb8,
	0xab, 0x6f, 0x62, 0x96, 0xda, 0x73, 0xb9, 0x89, 0xd6, 0x02, 0xab, 0xd4, 0xfd, 0x0a, 0xe6, 0x3f,
	0xb5, 0x68, 0x82, 0x4e, 0xc2, 0xeb, 0x30, 0x88, 0x56, 0xeb, 0x73, 0x6b, 0x82, 0x0b, 0xd0, 0x82,
	0xcd, 0x66, 0x75, 0xbe, 0x0e, 0x3f, 0x5b, 0x4a, 0x93, 0x9d, 0x5d, 0x5d, 0x5e, 0x5f, 0x84, 0x51,
	0x68, 0x4d, 0x71, 0x09, 0xf0, 0x6d, 0xdd, 0xbf, 0xaa, 0xee, 0x53, 0x98, 0x87, 0xf9, 0xbd, 0xd8,
	0xb9, 0x01, 0x2c, 0x86, 0xfa, 0xe2, 0x7b, 0x38, 0xb8, 0x64, 0x2b, 0x47, 0xea, 0x76, 0x5c, 0x32,
	0xf0, 0xf2, 0x12, 0xb4, 0x4e, 0xf4, 0x46, 0xe0, 0x22, 0xc9, 0x69, 0x27, 0x70, 0x13, 0xe3, 0xbb,
	0x83, 0x59, 0x8f, 0x5a, 0xdb, 0xb2, 0xfc, 0x3f, 0x0a, 0xe8, 0x1d, 0xce, 0xf1, 0x23, 0x18, 0x41,
	0x9a, 0xf6, 0x06, 0x8e, 0xed, 0x72, 0x62, 0x0d, 0xc0, 0xf6, 0xaa, 0x09, 0x7e, 0x02, 0x53, 0x36,
	0xed, 0x1b, 0x1d, 0x91, 0x4e, 0xfe, 0xb7, 0x88, 0x3b, 0xd9, 0x4f, 0xed, 0xaf, 0x1a, 0xfb, 0x5f,
	0x63, 0x53, 0x6f, 0x9e, 0xc8, 0x8f, 0xfe, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0xa2,
	0x40, 0x28, 0xfb, 0x02, 0x00, 0x00,
}
